sudo: false
os:
 - linux
language: d
d:
 - ldc-1.4.0
 - dmd
env:
 - ARCH="x86_64"
matrix:
  include:
    - {os: linux, d: ldc, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
branches:
  only:
    - master
script:
 - dub test --arch "$ARCH"